### PR TITLE
Added a bunch of more configs for appveyor

### PR DESCRIPTION
**Pull request by emoon**
Taken from this thread here https://users.rust-lang.org/t/rust-appveyor-windows-ci-scripts/4437 and this repro https://github.com/starkat99/appveyor-rust

It adds building on a combination of stable/unstable/nighly with msvc, gnu, etc. It adds a bunch of extra time for each build but increases coverage quite a bit.

### CODE REVIEW

**Comment by yupferris** [comment]
Thanks for this! Even though it's slower I'm a huge fan of running all the tests we can.

**Comment by emoon** [comment]
:+1:

**Comment by ryanhiebert** [comment]
Unless there's pushback, or someone else gets to it first, I'll add back that section in a new PR in a bit.

**Comment by yupferris** [comment]
Sorry @ryanhiebert , I merged before seeing that message! I'm still quite unfamiliar with appveyor, could you fix this?

**Comment by yupferris** [comment]
gotcha, sounds perfect; make a PR when you can and I'll merge it. Thanks!

**Comment by ryanhiebert** [comment]
@yupferris will do. You can be forgiven for not seeing the message before you merged. I hadn't written it yet. Unless you have a time machine ;-)

**Comment by yupferris** [comment]
maybe I do.....

**Pull request merged**
