### PR TITLE
LinWin alternative to Dash for documentation

### PR DESCRIPTION
**Pull request by simon-nicholls**
Zeal works with the same docsets, so I thought I'd add a link to the readme.

### CODE REVIEW

**Comment by gushromp** [comment]
Velocity for Windows also works with Dash docsets and is free (except for the Buy Me nag).
In my experience it's quite a bit faster than Zeal but the search functionality is more limited (or I haven't read enough documentation yet).

In any case, it's an option as well: https://velocity.silverlakesoftware.com/

**Comment by yupferris** [comment]
Hey guys, thanks! I haven't looked into those tools specifically yet, but I remember @emoon mentioning some drama that happened between the Dash author(s) and some free alternatives that were made to use the same docsets. If these are those tools, I'm honestly a bit iffy about promoting them - are these what you were talking about, @emoon ?

**Comment by simon-nicholls** [comment]
Ugg. That rebase went funky on me. I'm now just linking to Dash's own page that mentions Dash acknowledged alternatives.

It's probably more to the point that some of these alternatives are used in a very similar way to how you use Dash in your livecoding. I found myself unable to recommend an alternative GUI hex editor, since I always hit one snag or other, and resorted to `xxd`. e.g. `xxd -p -l 500 some.bin`

**Comment by yupferris** [comment]
Ah, this is great now; thanks for the update. Any reason in particular the rebase wasn't so smooth? Anything in particular I did that caused that?

I'll merge this on the next stream btw :)

**Comment by simon-nicholls** [comment]
I figure I was still a bit sleepy, and my fingers betrayed me somewhere along the line.

Am looking forward to the next adventure, though it's likely I'll watch it after the fact (currently on CET). I had been playing catch-up until now.

**Comment by DerekTurtleRoe** [comment]
@yupferris What drama was there between the developers? After watching the stream and finding out about Dash, I looked for a Windows solution and downloaded both Zeal and Velocity. I haven't tried either of them, but is there a reason I shouldn't use either? Like legally, ethically, etc?

**Comment by yupferris** [comment]
@vgturtle127 it looks like those are recommended on the official Dash site so I think you're fine. I don't know about the drama myself, I just remember @emoon mentioning it briefly on twitter at some point.

**Comment by emoon** [comment]
Yeah it seems someone used the docs at one point without permission but it seems it got settled a while later.

**Comment by DerekTurtleRoe** [comment]
@yupferris @emoon Oh, OK. Thanks guys.

**Comment by yupferris** [comment]
@simon-nicholls haha, I know that feeling! I'll actually be doing the next stream this evening CET. Will post update via twitter.

**Comment by DerekTurtleRoe** [comment]
@yupferris I'm so excited! My body is glowing with excitement! Why am I so happy? :laughing:

**Comment by yupferris** [comment]
@vgturtle127 lolwat XD

**Comment by DerekTurtleRoe** [comment]
@yupferris By the way, I just found this when I was looking for absolutely ridiculous things to try on Windows. :laughing: 

It seemed relevant to bring up in this PR.

https://github.com/areina/helm-dash

Do you want me to open a PR? :wink:

**Comment by yupferris** [comment]
hehe, I did actually know about that, but I'm too lazy to set it up and learn how to use it right now XD

**Comment by DerekTurtleRoe** [comment]
@yupferris Actually, I wanted to thank you for bringing Zeal to my attention. I can't believe I lived without this for so long! Especially with how many projects and languages and stuff I work with. It makes me way more productive!

**Comment by yupferris** [comment]
Don't thank me; thank @emoon :D

**Comment by DerekTurtleRoe** [comment]
@emoon Thank you, as well!

**Comment by emoon** [comment]
np :) Also regarding integration directly into editor. I prefer to have Dash separate. The only integration I have is to have a shortcut to search for something in Dash but I prefer to have the app separate and read it side by side.

**Comment by simon-nicholls** [comment]
While we're in the mood, I'd like to thank @yupferris for the Camellia name drop. The interwebs eventually informed me of their Vocaloid work, and well, I'm always up for a funky new Haskell typeclass :grin:

**Comment by yupferris** [comment]
haha, glad you like it :D

**Pull request merged**
