### PR TITLE
Add instruction opcode constants, and a wrapper class for instructions

### PR DESCRIPTION
**Pull request by birkenfeld**
which knows how to debug-print instructions in disassembly style.

Compared to the gist I posted, I cleaned the macros up a little bit, changed some names to be more descriptive, and added slightly more comments :)

### CODE REVIEW

**Comment by yupferris** [comment]
I've only skimmed it so far, will look into it more later; but this looks fantastic. Thanks! I'll most likely merge this on my next stream.

**Comment by yupferris** [comment]
Now that appveyor is set up correctly, could you rebase this onto the current master?

**Comment by birkenfeld** [comment]
Done! I also rebased it on top of my two smaller pull requests, since they both had conflicts with this branch.

**Comment by yupferris** [comment]
Ah, ok. I'll merge this one and close the others then on the next stream. I'll leave them open for now in case there's any further discussion.

**Comment by birkenfeld** [comment]
Added some tests, to give Travis/AppVeyor something to do :)

**Comment by yupferris** [comment]
Hey, so I've been thinking about some of these contributions, and I've written kindof a braindump here. Would love to hear your thoughts on it: https://gist.github.com/yupferris/f8eeb712bdb068891ecd

**Comment by yupferris** [comment]
Thanks again for this, I'm going to close it tho due to what we discussed :)

**Pull request closed without merging**
