### PR TITLE
Use Default for initializing the Default Fields

### PR DESCRIPTION
**Pull request by CryZe**
It's possible to use a combination of Default and a normal Initializer to keep the default fields while still manually specifying the values of some fields.

### CODE REVIEW

**Comment by yupferris** [comment]
Thanks for this! I've looked over the code though, and I have a bit of a concern that while using `Default` like this is nice to write less code, it also makes it possible to instantiate these struct's _without_ using `new` (one could just use `default`), in which case the dependencies the structs need to function properly (in particular `pif_rom` for `Interconnect`) wouldn't necessarily have been initialized properly.

**Comment by CryZe** [comment]
Yeah, that's unfortunately true. It would be cool if Rust would allow you to write private trait implementations.
You can close this if you don't want to merge this then.

**Comment by yupferris** [comment]
Yeah, I think I'll close this for that reason. Thanks again though; I probably wouldn't've thought of that issue had I not actually seen it done first :)

**Comment by CryZe** [comment]
How does Rust actually import impls? Maybe we could move the Default implementations into a module that isn't visible to the outside?

**Comment by yupferris** [comment]
Afaik trait impl's are always going to be public by definition

**Comment by emoon** [comment]
So a trick that I use (which I actually found here)

https://github.com/nagisa/rust_libloading/blob/master/src/lib.rs

Now this works good in abstracting away different OS implementations (I use this in minfb) but perhaps overkill in this case.

**Comment by yupferris** [comment]
Reopening because of the discussion :)

**Comment by yupferris** [comment]
@emoon: yeah, I don't think that solution is appropriate to this problem, which is really just "can we write a bit less code without doing something drastic" :)

**Comment by yupferris** [comment]
feels too heavyweight for sure (good trick to know tho!)

**Comment by emoon** [comment]
Agreed. Just wanted to share as it's quite nice in some case :)

**Comment by yupferris** [comment]
Yeah, it is nice, thanks!

**Comment by yupferris** [comment]
@CryZe are you still planning on playing with this, or should I close this PR?

**Comment by CryZe** [comment]
I think this can be closed.

**Comment by yupferris** [comment]
thanks!

**Pull request closed without merging**
