### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by roshats**
_Magic_ file with contribution notes. 

See https://help.github.com/articles/setting-guidelines-for-repository-contributors/ .

### CODE REVIEW

**Comment by yupferris** [comment]
Fantastic, thanks! Any chance you can squash the commits?

**Comment by emoon** [comment]
@yupferris good to know that you can also squash them when you merge the PR (directly in the GitHub UI when you select merge -> drop down and squash commits)

**Comment by roshats** [comment]
@yupferris, done. @emoon, thanks, I didn't know that.

**Comment by yupferris** [comment]
Oh wow I also didn't know that, haha. Thanks for the tip @emoon and thanks for squashing @roshats :)

Normally I wait until the next stream to accept PR's but since this doesn't affect the code I think I'll take it now (and mention it on the next stream ofc).

**Comment by emoon** [comment]
np :) I found out about it like two days ago also :)

**Pull request merged**
