### PR TITLE
Use Travis CI

### PR DESCRIPTION
**Pull request by ryanhiebert**
Before merging this Pull Request, go to https://travis-ci.org/profile and enable this repository. That way we'll get builds of the master branch immediately.

This includes basic configuration to test on rust stable, with Travis CI container builds, and only looking at the master branch and pull requests that are opened against the master branch.

Add a badge to the readme to report on the current build status of the master branch.

The commands run for testing by default are

``` sh
cargo build --verbose
cargo test --verbose
```

See https://docs.travis-ci.com/user/languages/rust for more information.

### CODE REVIEW

**Comment by yupferris** [comment]
Hey thanks!

A couple things:
- Can we make sure this also gets tested on beta and nightly as well?
- I would like to receive emails for failed builds
- Tiny thing, but I'd like the badge to be on the same line as the title in the readme :)

For references for what I'd like, see https://github.com/yupferris/butterball/blob/master/.travis.yml and https://github.com/yupferris/butterball/blob/master/README.md .

**Comment by ryanhiebert** [comment]
Sure thing. Would you also like to have those `--version` lines?

**Comment by yupferris** [comment]
Ah yeah, forgot to mention those. Sure, why not? :)

**Comment by ryanhiebert** [comment]
Nice, we've already got our first build, on this PR!

**Comment by yupferris** [comment]
Looks great, thanks! Normally I wait to merge this until I'm on stream but I think it's helpful to have this now so any other PR's coming in can also be tested. I'll still go over this change on the stream ofc, but I'll merge it now. Sound good?

**Comment by ryanhiebert** [comment]
:+1: I wrote it because of your comment on the other PR.

**Comment by yupferris** [comment]
Gotcha, good call :)

**Pull request merged**
