### PR TITLE
Cleanup some alignment for my OCD

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by yupferris** [comment]
Haha, thanks for this! One issue I have with it however is I don't like to remove parens between certain operators. It's much too easy to forget that `<<`/`>>` bind stronger than `|`, so I'd like to keep the parens there. Perhaps we can compromise?

``` rust
((self.pif_rom[(rel_addr + 0) as usize] as u32) << 24) |
((self.pif_rom[(rel_addr + 1) as usize] as u32) << 16) |
((self.pif_rom[(rel_addr + 2) as usize] as u32) <<  8) |
((self.pif_rom[(rel_addr + 3) as usize] as u32) <<  0)
```

**Comment by ghost** [comment]
looks great!

**Comment by yupferris** [comment]
Cool, if you could replace your commit with that or add and squash I can accept this :)

**Comment by ghost** [comment]
I believe that should do it. I don't make a pull requests often.

**Comment by yupferris** [comment]
This is great! As per my "I don't want to write any code except on the stream" I'd like to go over this PR and merge it live as well. Will do on my next stream!

**Comment by yupferris** [comment]
Also thanks!

**Pull request merged**
