### PR TITLE
Use Clap for parsing the Command Line Arguments

### PR DESCRIPTION
**Pull request by CryZe**
The Clap crate is a simple to use, efficient, and full featured library for parsing command line arguments and subcommands when writing console, or terminal applications. It even shows a useful help message and tells you which arguments you forgot to specify if you forgot some.

### CODE REVIEW

**Comment by birkenfeld** [comment]
:+1:

**Comment by yupferris** [comment]
Hey, so I've been thinking about some of these contributions, and I've written kindof a braindump here. Would love to hear your thoughts on it: https://gist.github.com/yupferris/f8eeb712bdb068891ecd

**Comment by CryZe** [comment]
Yeah, I thought so too. I wouldn't have implemented this, but then people began doing really large PRs, which led me to believe something simple like this wouldn't be too much either. But yeah, you really should just do most of this on the stream yourself. 

At least you know about Clap now and have a reference implementation :)

**Comment by yupferris** [comment]
Yeah, it's my bad for not setting precedence in the first place. Thanks for this though, it will be quite helpful and I'll certainly be doing this :) I'll open an issue about it now.

**Comment by yupferris** [comment]
https://github.com/yupferris/rustendo64/issues/25

**Pull request closed without merging**
