### PR TITLE
Add links to legal ROMs, and also remove TODO

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**
Creating the PR you wanted. :smile: 

Let me know if I can help in any other way!

### CODE REVIEW

**Comment by yupferris** [comment]
Awesome, thanks! I'll merge this during the next stream :)

**Comment by yupferris** [comment]
Fixes #24

**Comment by DerekTurtleRoe** [comment]
@yupferris This fixes #23 , not 24. :smile:

**Comment by yupferris** [comment]
Lol, indeed. I totally typed the # and only scanned the suggestions, saw something about legal roms, and went for it. Turns out #24 is this PR :D

**Comment by DerekTurtleRoe** [comment]
@yupferris Although, in a roundabout way, the PR would be fixed by merging it. :laughing:

**Comment by yupferris** [comment]
True dat!

**Pull request merged**
