### PR TITLE
Use wrapping add for load address offsets.

### PR DESCRIPTION
**Pull request by birkenfeld**
Otherwise in debug mode you will get an overflow panic with negative offsets.

### CODE REVIEW

**Comment by yupferris** [comment]
Good call, thanks! I'll merge this on the next stream.

**Comment by CryZe** [comment]
The offset is a signed 16-bit integer. Why don't we just use actual signed addition instead of abusing unsigned addition? Rust has built-in safety checks for wrapping and that's good, but obviously using unsigned addition will not work well with these checks in place, which is why this PR turns them off. But with signed addition we can keep the checks without having to turn off Rust's safety features (and without having to abuse types in weird ways).

**Comment by emoon** [comment]
I was actually thinking that as well on the stream (is that offset really correct now?)
Just to show I did this:

https://play.rust-lang.org/?gist=c6ff4459946581d7576c&version=stable

**Comment by birkenfeld** [comment]
I would agree, but: signed addition just reduces the potential for overflow. Try the playpen example with `base = 0x8000_0000_0000_0000`.  Granted, that address won't be relevant for this emulator, but it is nevertheless less correct code.

Also, I am not happy with the characterization of "abusing types in weird ways". `wrapping_add` is not unsafe, it is a perfectly well-defined operation (in some ways, more well-defined than normal addition), and just what the processor does here.

**Comment by yupferris** [comment]
> Also, I am not happy with the characterization of "abusing types in weird ways". wrapping_add is not unsafe, it is a perfectly well-defined operation (in some ways, more well-defined than normal addition), and just what the processor does here.

I think they're referring to me casting to `u64` instead of `i64` which arguably captures the "signed-ness" semantics better. So I can understand using `i64` there instead of `u64`, which makes sense.

@birkenfeld has a very valid point though that we can still overflow, and that's what I was thinking when I wanted to go straight for `u64` (even though I didn't do `wrapping_add` on the stream).

Then we come to the issue with whether or not `wrapping_add` has overloads for `u64` + `i64`, and after a _dashingly quick_ skim through the docs (see what I did there?) I wasn't able to find one. Only https://doc.rust-lang.org/std/primitive.u64.html#method.wrapping_add appears to exist (which is `u64` + `u64`), and in that case going to `u64` and `wrapping_add` like in this PR seems like the correct solution.

**Comment by CryZe** [comment]
0x8000_0000_0000_0000 only underflows because it's literally the most negative number for i64. In my opinion the code SHOULD panic if you are that far into the negative numbers and even wrap around. In fact, it should probably already panic if you reach any negative address, but that's probably not possible without an explicit assertion. So I don't see any problem with using signed addition here.

**Comment by birkenfeld** [comment]
> 0x8000_0000_0000_0000 only underflows because it's literally the most negative number for i64. 

Which doesn't matter since memory addresses are unsigned. Interpreting them as signed puts an artificial boundary in the middle of the address space for no good reason.

**Comment by CryZe** [comment]
Okay, I guess that's true. A N64 wouldn't panic either, so I guess wrapping_add would be more accurate to the actual architecture.

**Comment by yupferris** [comment]
For the record I'm still planning on merging this on the next stream :)

**Pull request merged**
